theme: jekyll-theme-minimal
markdown: CommonMarkGhPages
title: EOSC-Life Workflow Hub project
email: info@esciencelab.org.uk
description: > # this means to ignore newlines until "baseurl:" 
  Project pages for developing and running the WorkflowHub, 
  a European-wide registry of scientific workflows funded by 
  EOSC-Life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://about.workflowhub.eu" # the base hostname & protocol for your site
github_username:  workflowhub-eu
encoding: UTF-8
permalink: pretty

logo: logo/workflowhub-square.svg
